spring:
  application:
    name: room-rental-api
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/roomrental}
    username: ${JDBC_DATABASE_USERNAME:roomrental}
    password: ${JDBC_DATABASE_PASSWORD:roomrental}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
